export const DISEASES = [
  {
    label: "Tomato___Late_blight",
    crop: "Tomato",
    disease: "Late blight",
    remedies: [
      "Remove and destroy infected leaves and stems immediately.",
      "Apply copper-based fungicide every 7-10 days during wet conditions.",
      "Ensure proper spacing between plants to improve airflow and reduce humidity.",
      "Use late blight-resistant tomato varieties.",
      "Water at the base of the plant, avoiding overhead watering to reduce leaf wetness.",
      "Clean tools and equipment regularly to avoid spreading spores.",
      "Rotate crops with non-solanaceous plants like beans or corn.",
      "Use organic treatments like neem oil or biological fungicides (e.g., Bacillus subtilis).",
      "Mulch around the plants to avoid soil splash during rain.",
      "Monitor for early blight symptoms such as dark, water-soaked lesions.",
    ],
    causes: [
      "Caused by the Phytophthora infestans fungus.",
      "Thrives in warm, wet conditions, especially during rainy weather.",
      "Spread by wind, rain, and insects like aphids.",
      "Infected plant debris from previous seasons can harbor spores.",
      "Poor drainage and excessive humidity around plants.",
      "Presence of infected transplants from nurseries.",
      "Overcrowded plants restricting airflow.",
    ],
    severity: "high",
  },
  {
    label: "Tomato___healthy",
    crop: "Tomato",
    disease: "healthy",
    remedies: [
      "Continue with regular plant care, ensuring proper nutrition.",
      "Monitor plants daily for early disease detection.",
      "Ensure proper irrigation—water the soil, not the leaves.",
      "Prune dead or damaged leaves to promote healthy growth.",
      "Mulch to retain soil moisture and prevent weed growth.",
      "Use organic fertilizers and soil amendments for healthy growth.",
      "Maintain optimal spacing between plants to avoid overcrowding.",
      "Keep the growing area free of weeds that may harbor pests.",
    ],
    causes: [
      "Healthy growth due to proper care, good soil, and balanced nutrition.",
      "Thrives in well-drained soil with adequate sunlight (6-8 hours per day).",
      "Pruning and timely harvesting to prevent disease spread.",
      "Adequate watering, avoiding waterlogging and ensuring good soil moisture.",
    ],
    severity: "low",
  },
  {
    label: "Grape___healthy",
    crop: "Grape",
    disease: "healthy",
    remedies: [
      "Continue regular vineyard maintenance with balanced fertilization.",
      "Prune dead or weak branches and vines to promote strong growth.",
      "Ensure proper irrigation—deep watering during dry spells.",
      "Regularly inspect for pests such as aphids or scale insects.",
      "Use companion plants or traps for natural pest control.",
      "Mulch around the base to retain moisture and prevent weed growth.",
      "Monitor for early signs of fungal infections (e.g., powdery mildew).",
      "Thin out dense areas of growth to allow airflow and sunlight.",
    ],
    causes: [
      "Healthy plants due to optimal sunlight, water, and soil.",
      "Proper spacing of vines to ensure good airflow and reduce humidity.",
      "Routine pest management and vineyard sanitation practices.",
      "Use of resistant grape varieties to avoid common fungal infections.",
    ],
    severity: "low",
  },
  {
    label: "Orange___Haunglongbing_(Citrus_greening)",
    crop: "Orange",
    disease: "Haunglongbing (Citrus greening)",
    remedies: [
      "Remove and destroy infected leaves immediately to prevent spread.",
      "Apply copper-based fungicide at regular intervals during high humidity.",
      "Ensure adequate spacing between trees to improve airflow and sunlight exposure.",
      "Use disease-resistant citrus varieties that are more tolerant to greening.",
      "Avoid overhead watering to minimize leaf wetness and fungal growth.",
      "Regularly disinfect pruning tools and equipment to prevent disease transmission.",
      "Rotate crops and avoid planting citrus in areas with previous infection.",
      "Mulch around the base of trees to reduce soil splash and help with water retention.",
      "Monitor trees for early symptoms such as yellowing and leaf drop, and take immediate action.",
      "Consider using organic treatments like neem oil or biological insecticides to control vector insects.",
    ],
    causes: [
      "Caused by the *Candidatus Liberibacter* bacteria, transmitted by psyllid insects.",
      "Triggered by warm, humid conditions, particularly during the rainy season.",
      "Spread via insect vectors like the Asian citrus psyllid, which transmits the bacterium.",
      "Poor drainage and overwatering create a favorable environment for the disease.",
      "Infected seeds, transplants, or poorly disinfected tools can introduce the bacteria.",
      "Neglecting to manage vector insects or not removing infected plant material can exacerbate the issue.",
      "Prolonged exposure to infected plant debris from previous seasons.",
    ],
    severity: "medium",
  },
  {
    label: "Soybean___healthy",
    crop: "Soybean",
    disease: "healthy",
    remedies: [
      "Continue regular care, ensuring optimal soil conditions and sufficient irrigation.",
      "Monitor the crop for early signs of pests or diseases, especially during high humidity.",
      "Provide consistent nutrition with balanced fertilizers to maintain plant health.",
      "Ensure proper spacing between plants to allow for air circulation and sunlight penetration.",
      "Mulch to retain moisture and reduce competition from weeds.",
      "Avoid waterlogging by ensuring proper drainage and avoiding overhead watering.",
      "Remove any dead or diseased leaves to promote healthier growth.",
      "Rotate crops to prevent soil-borne diseases and to maintain soil fertility.",
      "Inspect plants regularly for signs of nutrient deficiencies, such as yellowing leaves.",
      "Use organic or natural pesticides only if necessary to control pests.",
    ],
    causes: [
      "Healthy growth is a result of balanced nutrition, optimal water management, and pest control.",
      "Well-drained soil with good aeration and access to sunlight promotes strong growth.",
      "Consistent irrigation and regular maintenance prevent environmental stress on the plants.",
      "Careful monitoring and timely intervention ensure the crop stays disease-free.",
    ],
    severity: "low",
  },
  {
    label: "Squash___Powdery_mildew",
    crop: "Squash",
    disease: "Powdery mildew",
    remedies: [
      "Remove and destroy infected leaves to prevent further spread of the disease.",
      "Apply sulfur-based fungicides or other fungicides effective against powdery mildew.",
      "Ensure proper spacing between plants to improve airflow and reduce humidity around the leaves.",
      "Use powdery mildew-resistant squash varieties when possible.",
      "Avoid overhead watering, as it encourages fungal growth on the leaves.",
      "Regularly disinfect gardening tools to prevent cross-contamination between plants.",
      "Rotate crops annually to prevent the buildup of mildew spores in the soil.",
      "Mulch around the plants to prevent soil splash and reduce weed competition.",
      "Monitor plants daily for white, powdery spots that are characteristic of mildew.",
      "Consider organic treatments like neem oil or bicarbonate-based solutions for fungal control.",
    ],
    causes: [
      "Caused by fungal pathogens, primarily *Erysiphe cichoracearum* and *Sphaerotheca fuliginea*.",
      "Triggered by warm, dry conditions with high humidity, especially in late summer.",
      "Spread by wind, rain, and contact with infected plants or tools.",
      "Overhead watering and poor plant spacing increase humidity and favor fungal growth.",
      "Infected seeds, plant material, or tools can introduce the disease into a new area.",
      "Neglecting to remove infected debris or failed crops can contribute to spore buildup.",
      "Rapid temperature fluctuations, combined with still air, can exacerbate the spread.",
    ],
    severity: "medium",
  },
  {
    label: "Potato___healthy",
    crop: "Potato",
    disease: "healthy",
    remedies: [
      "Continue regular care, ensuring proper irrigation and soil fertility.",
      "Monitor for early signs of pests, especially aphids and beetles.",
      "Ensure optimal spacing between plants to improve airflow and reduce overcrowding.",
      "Remove dead or damaged leaves to prevent potential disease outbreaks.",
      "Maintain good soil drainage to avoid waterlogging and root rot.",
      "Use disease-resistant potato varieties to reduce the risk of infection.",
      "Mulch around the base to retain moisture and suppress weeds.",
      "Rotate crops to prevent soil depletion and reduce pathogen buildup.",
      "Keep the growing area free of infected debris and fallen plant material.",
      "Ensure adequate sunlight (at least 6 hours a day) for healthy growth.",
    ],
    causes: [
      "Healthy growth due to proper care, balanced nutrition, and optimal watering.",
      "Well-drained soil with good aeration and access to sunlight.",
      "Consistent irrigation that prevents water stress without overwatering.",
      "Regular monitoring to detect pests and diseases early, preventing spread.",
      "Careful crop rotation to prevent soil-borne diseases and maintain soil health.",
    ],
    severity: "low",
  },
  {
    label: "Corn_(maize)___Northern_Leaf_Blight",
    crop: "Corn",
    disease: "Northern Leaf Blight",
    remedies: [
      "Remove and destroy infected leaves immediately to reduce the spread of spores.",
      "Apply fungicides specifically effective against *Exserohilum turcicum*.",
      "Ensure proper plant spacing to improve airflow and reduce humidity around leaves.",
      "Use disease-resistant corn varieties to reduce the risk of infection.",
      "Avoid overhead irrigation to minimize leaf wetness and fungal growth.",
      "Disinfect tools regularly to prevent cross-contamination between plants.",
      "Rotate crops, especially avoiding planting corn in the same area for consecutive seasons.",
      "Mulch to reduce soil splash and protect plants from further infection.",
      "Monitor plants regularly for early signs such as long, narrow lesions on leaves.",
      "Use organic treatments like neem oil or biocontrol agents to manage fungal spread.",
    ],
    causes: [
      "Caused by the fungus *Exserohilum turcicum*, which thrives in humid conditions.",
      "Triggered by prolonged periods of high humidity and rainfall, which promote spore germination.",
      "Spread by wind and rain, which disperse the fungal spores to healthy plants.",
      "Infected crop debris from previous seasons can act as a source of inoculum.",
      "Inadequate plant spacing and poor air circulation around corn plants encourage disease spread.",
      "Fungal spores can be transmitted through tools, water, and human activity.",
      "Excessive irrigation or poor drainage conditions increase leaf wetness and favor fungal development.",
    ],
    severity: "high",
  },
  {
    label: "Tomato___Early_blight",
    crop: "Tomato",
    disease: "Early blight",
    remedies: [
      "Remove and destroy infected leaves immediately to reduce disease spread.",
      "Apply copper-based fungicides or other systemic fungicides for early blight control.",
      "Ensure proper plant spacing to promote airflow and reduce leaf humidity.",
      "Use disease-resistant tomato varieties that are less susceptible to early blight.",
      "Avoid overhead watering to prevent water from splashing onto leaves and promoting infection.",
      "Disinfect pruning tools and equipment regularly to prevent the spread of spores.",
      "Rotate crops with non-solanaceous plants to avoid soil-borne pathogens.",
      "Mulch to reduce soil splash and protect plants from splattering infected soil.",
      "Monitor plants daily for characteristic signs such as concentric rings or dark spots on leaves.",
      "Consider organic treatments like neem oil or biological fungicides for prevention.",
    ],
    causes: [
      "Caused by the fungal pathogen *Alternaria solani*, which thrives in warm, wet conditions.",
      "Triggered by high humidity and excessive rainfall, which support fungal spore germination.",
      "Spread by rain, wind, and infected plant debris from previous seasons.",
      "Infected seeds, transplants, or contaminated tools can introduce spores into the garden.",
      "Poor plant spacing and high humidity increase the likelihood of fungal infection.",
      "Inadequate air circulation around plants can allow the fungus to spread more easily.",
      "Failure to remove fallen leaves and infected debris contributes to fungal spore accumulation.",
    ],
    severity: "high",
  },
  {
    label: "Tomato___Septoria_leaf_spot",
    crop: "Tomato",
    disease: "Septoria leaf spot",
    remedies: [
      "Remove and destroy infected leaves to prevent further spread.",
      "Apply copper-based fungicide or fungicides specifically for septoria.",
      "Ensure proper plant spacing to improve airflow around plants.",
      "Use disease-resistant tomato varieties to reduce the risk of infection.",
      "Avoid overhead watering to keep the leaves dry and prevent fungal growth.",
      "Disinfect tools regularly to avoid transferring spores from infected plants.",
      "Rotate crops to prevent soil-borne pathogens from accumulating in the soil.",
      "Mulch around the base of the plant to reduce soil splash and lower the risk of infection.",
      "Monitor plants daily for early signs, such as small dark spots with concentric rings.",
      "Use organic treatments like neem oil to help prevent fungal outbreaks.",
    ],
    causes: [
      "Caused by the fungal pathogen *Septoria lycopersici*.",
      "Spread by water droplets, wind, or contaminated tools and equipment.",
      "Excessive moisture on the plant leaves, especially during rainy seasons.",
      "Poor air circulation in the plant canopy allows the fungus to thrive.",
      "Infected plant debris or soil from previous seasons can act as a reservoir for the disease.",
      "Infected seeds or seedlings may introduce the fungus into the garden.",
      "Wet, humid conditions provide the ideal environment for fungal spore germination.",
    ],
    severity: "high",
  },
  {
    label: "Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot",
    crop: "Corn",
    disease: "Cercospora leaf spot Gray leaf spot",
    remedies: [
      "Remove and destroy infected leaves to prevent further spread of the disease.",
      "Apply fungicides that are effective against *Cercospora* species.",
      "Ensure proper plant spacing to improve airflow around the plants.",
      "Use disease-resistant corn varieties to reduce susceptibility.",
      "Avoid overhead watering to keep the leaves dry and reduce the spread of spores.",
      "Disinfect tools regularly to prevent the spread of fungal spores.",
      "Rotate crops and avoid planting corn in the same area year after year.",
      "Mulch to prevent soil splash and reduce the spread of spores from infected soil.",
      "Monitor plants regularly for early symptoms, such as dark, angular spots on leaves.",
      "Use organic fungicides like neem oil or biological agents for fungal control.",
    ],
    causes: [
      "Caused by the fungal pathogen *Cercospora zeae-maydis*.",
      "Spread by wind and rain that carry spores to healthy plants.",
      "Wet conditions, especially prolonged periods of leaf wetness, favor fungal infection.",
      "Poor crop rotation and continuous corn planting increase the risk of infection.",
      "Infected plant debris can harbor the fungus and infect new crops.",
      "Poor soil drainage and overhead watering increase humidity and favor fungal growth.",
      "The disease is more prevalent during periods of high heat and humidity.",
    ],
    severity: "high",
  },
  {
    label: "Strawberry___Leaf_scorch",
    crop: "Strawberry",
    disease: "Leaf scorch",
    remedies: [
      "Remove and destroy infected leaves to reduce the spread of infection.",
      "Apply copper-based fungicides or fungicides specifically for leaf scorch.",
      "Ensure proper spacing between plants to improve airflow and reduce humidity.",
      "Use disease-resistant strawberry varieties to prevent future outbreaks.",
      "Avoid overhead watering to keep the leaves dry and reduce the likelihood of infection.",
      "Disinfect tools regularly to avoid spreading the pathogen between plants.",
      "Rotate crops to prevent buildup of pathogens in the soil.",
      "Mulch to prevent soil splash and reduce the risk of infection from the soil.",
      "Monitor plants daily for early symptoms, such as yellowing or browning edges on leaves.",
      "Use organic treatments like neem oil or compost tea to improve plant health.",
    ],
    causes: [
      "Caused by fungal or bacterial pathogens, including *Bipolaris* species.",
      "Triggered by high humidity and poor airflow around the plants.",
      "Infection is more common in stressed plants, often from overwatering or inadequate soil drainage.",
      "Soil-borne pathogens and infected plant debris from previous seasons may contribute to the disease.",
      "Excessive leaf wetness, particularly in poorly drained soil, creates an environment conducive to infection.",
      "Improper sunlight or nutrient imbalances can increase susceptibility to leaf scorch.",
      "Infected tools, water, or human activity can transmit the disease from one plant to another.",
    ],
    severity: "medium",
  },
  {
    label: "Peach___healthy",
    crop: "Peach",
    disease: "healthy",
    remedies: [
      "Maintain proper watering and irrigation practices to avoid water stress.",
      "Ensure optimal spacing between trees for airflow and reduced disease pressure.",
      "Use disease-resistant peach varieties where available.",
      "Disinfect tools regularly to prevent spreading any potential pathogens.",
      "Rotate crops and remove any fallen fruit or leaves to prevent fungal buildup.",
      "Provide adequate sunlight to ensure healthy plant growth and fruiting.",
      "Ensure good soil fertility and proper pH for healthy peach growth.",
      "Prune dead or damaged branches regularly to improve tree health.",
      "Use organic treatments like neem oil for pest management and overall tree health.",
      "Monitor plants regularly for pests or disease signs, especially during the growing season.",
    ],
    causes: [
      "Healthy growth due to optimal care, watering, and nutrient management.",
      "Well-drained soil with good aeration and proper irrigation.",
      "Sunlight and air circulation are crucial for preventing fungal and pest issues.",
      "Regular monitoring for pests and disease helps maintain healthy trees.",
      "Proper care practices such as pruning and soil management promote tree health.",
    ],
    severity: "low",
  },
  {
    label: "Apple___Apple_scab",
    crop: "Apple",
    disease: "Apple scab",
    remedies: [
      "Remove and destroy infected leaves to prevent the spread of the pathogen.",
      "Apply fungicides before the onset of symptoms, especially during wet weather.",
      "Ensure proper spacing between trees to improve airflow and reduce humidity.",
      "Use disease-resistant apple varieties to reduce the chance of infection.",
      "Avoid overhead watering to reduce leaf wetness, which promotes fungal growth.",
      "Disinfect tools and equipment to prevent spreading spores from infected trees.",
      "Rotate crops and remove any infected plant material to reduce pathogen presence.",
      "Mulch to prevent soil splash and to help keep the lower leaves dry.",
      "Monitor trees regularly for early signs, including dark, round lesions on leaves.",
      "Use organic fungicides or neem oil as preventative treatments for apple scab.",
    ],
    causes: [
      "Caused by the fungus *Venturia inaequalis*.",
      "Spread through water droplets, wind, and infected leaves or fruit.",
      "Infected fallen leaves from previous seasons are a major source of inoculum.",
      "Cool, wet conditions are ideal for the fungus to spread and cause infection.",
      "Infected seeds or transplants can introduce the disease into a new area.",
      "High humidity and rain help spread spores, while dry conditions limit the disease.",
    ],
    severity: "medium",
  },
  {
    label: "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    crop: "Tomato",
    disease: "Tomato Yellow Leaf Curl Virus",
    remedies: [
      "Remove and destroy infected leaves to reduce viral spread.",
      "Apply insecticides to control the aphids that spread the virus.",
      "Use resistant tomato varieties to prevent infection from the virus.",
      "Disinfect tools regularly to prevent spreading the virus between plants.",
      "Avoid planting tomatoes in areas with high aphid populations.",
      "Rotate crops to reduce the buildup of viral vectors in the soil.",
      "Mulch to prevent soil splash and help control weed growth, which may harbor pests.",
      "Monitor plants regularly for early symptoms such as curled and yellowing leaves.",
      "Use insecticidal soaps or neem oil to reduce aphid populations.",
      "Ensure healthy plant nutrition to reduce the impact of the virus on plant growth.",
    ],
    causes: [
      "Caused by the *Tomato Yellow Leaf Curl Virus* (TYLCV), spread by whiteflies.",
      "Spread primarily by aphids or whiteflies that feed on infected plants.",
      "Overcrowding, poor ventilation, and high temperatures stress plants and increase viral spread.",
      "High aphid populations in the area contribute to faster transmission of the virus.",
      "Infected seeds or transplants may also introduce the virus into a new garden.",
      "Prolonged periods of heat and drought can make plants more susceptible to viral infections.",
    ],
    severity: "high",
  },
  {
    label: "Tomato___Bacterial_spot",
    crop: "Tomato",
    disease: "Bacterial spot",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by bacterial pathogens like *Xanthomonas* species.",
      "Spread by rain, water droplets, insects, or contaminated equipment.",
      "Humidity and poor airflow around the plant increase the likelihood of infection.",
      "Infected seeds, transplants, or contaminated soil can introduce the bacteria.",
      "Watering plants overhead spreads bacteria onto healthy plant surfaces.",
      "Bacterial spots typically form on lower, older leaves first and then spread.",
      "Rapid temperature fluctuations or stress can make plants more susceptible.",
      "Neglecting to remove fallen infected plant debris can harbor bacteria.",
    ],
    severity: "high",
  },
  {
    label: "Apple___Black_rot",
    crop: "Apple",
    disease: "Black rot",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by the fungus *Botryosphaeria obtusa*.",
      "Spread by wind, rain, and insect vectors that carry spores.",
      "Infected plant material, particularly mummified fruit, can harbor the pathogen.",
      "Excessive moisture on leaves from overhead watering facilitates the spread.",
      "Infected soil and tools can help propagate the disease to new plants.",
      "Prolonged periods of wet weather increase the risk of infection.",
      "Plant stress due to poor soil conditions or nutrient imbalances can make plants more susceptible.",
    ],
    severity: "medium",
  },
  {
    label: "Blueberry___healthy",
    crop: "Blueberry",
    disease: "healthy",
    remedies: [
      "Ensure proper plant spacing for airflow",
      "Disinfect tools regularly",
      "Mulch to prevent soil splash",
      "Monitor plants regularly for early signs of stress or pests",
      "Provide proper irrigation and avoid overwatering",
      "Use organic treatments like neem oil if pest or fungal problems arise",
    ],
    causes: [
      "Healthy growth due to adequate care, including good soil management and water control.",
      "Proper spacing between plants to improve airflow and reduce disease pressure.",
      "Sunlight, proper pruning, and pest management contribute to overall plant health.",
    ],
    severity: "low",
  },
  {
    label: "Cherry_(including_sour)___Powdery_mildew",
    crop: "Cherry (including sour)",
    disease: "Powdery mildew",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by fungal pathogens like *Podosphaera* species.",
      "Spreads through airborne fungal spores during wet conditions.",
      "Humidity and poor air circulation are key triggers for the fungus.",
      "Water droplets and infected tools or human activity can spread the spores.",
      "Fungal growth can appear as a white powdery coating on leaves and stems.",
      "Plants under stress or in shaded areas are more likely to suffer from powdery mildew.",
    ],
    severity: "medium",
  },
  {
    label: "Peach___Bacterial_spot",
    crop: "Peach",
    disease: "Bacterial spot",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by bacterial pathogens, notably *Xanthomonas pruni*.",
      "Spread by splashing water, wind, and insects.",
      "Prolonged wet conditions and high humidity are favorable for bacterial growth.",
      "Infected seeds or transplants may introduce bacteria to new gardens.",
      "Neglecting to remove infected plant material or debris can harbor the bacteria.",
      "Bacterial spots often begin on the lower leaves before moving upward on the plant.",
    ],
    severity: "high",
  },
  {
    label: "Apple___Cedar_apple_rust",
    crop: "Apple",
    disease: "Cedar apple rust",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by the fungus *Gymnosporangium juniperi-virginianae*.",
      "Requires both apple and eastern red cedar trees to complete its life cycle.",
      "Spread by wind-borne spores released from cedar trees.",
      "Humidity and wet conditions encourage the spread of spores from infected trees.",
      "Infected fallen leaves or fruit contribute to the propagation of the disease.",
    ],
    severity: "medium",
  },
  {
    label: "Tomato___Target_Spot",
    crop: "Tomato",
    disease: "Target Spot",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by the fungus *Corynespora cassiicola*.",
      "Infected plant debris or soil harbor fungal spores.",
      "High humidity, poor airflow, and wet conditions increase infection risk.",
      "The disease causes dark, concentric, target-like lesions on leaves.",
      "Spread through rain or overhead watering that splashes spores onto healthy plants.",
    ],
    severity: "high",
  },
  {
    label: "Pepper,_bell___healthy",
    crop: "Pepper, bell",
    disease: "healthy",
    remedies: [
      "Ensure proper plant spacing for airflow",
      "Disinfect tools regularly",
      "Mulch to reduce soil splash",
      "Monitor plants regularly for early signs of stress or pests",
      "Provide proper irrigation and avoid overwatering",
      "Use organic treatments like neem oil if pest or fungal problems arise",
    ],
    causes: [
      "Healthy growth due to proper irrigation, nutrient management, and pest control.",
      "Adequate spacing and sunlight contribute to plant vitality and resilience.",
      "Proper soil conditions and good watering practices prevent most diseases.",
    ],
    severity: "low",
  },
  {
    label: "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    crop: "Grape",
    disease: "Leaf blight (Isariopsis Leaf Spot)",
    remedies: [
      "Remove and destroy infected leaves",
      "Apply copper-based fungicide",
      "Ensure proper plant spacing for airflow",
      "Use disease-resistant varieties",
      "Avoid overhead watering",
      "Disinfect tools regularly",
      "Rotate crops to prevent soil-borne pathogens",
      "Mulch to reduce soil splash",
      "Monitor plants daily for early signs",
      "Use organic treatments like neem oil",
    ],
    causes: [
      "Caused by the fungus *Isariopsis farlowii*.",
      "Spread by rain, irrigation water, or wind.",
      "Prolonged wet conditions on leaves, particularly during flowering and fruiting.",
      "Infected grapevines, soil, or tools may spread the disease.",
      "Moist environments favor the germination of fungal spores, leading to rapid spread.",
    ],
    severity: "high",
  },
  {
    label: "Potato___Late_blight",
    crop: "Potato",
    disease: "Late blight",
    remedies: [
      "Remove and destroy infected leaves and stems immediately",
      "Apply systemic fungicides specifically for late blight, such as those containing mefenoxam or chlorothalonil",
      "Ensure proper plant spacing to improve airflow and reduce humidity",
      "Use resistant potato varieties when available",
      "Avoid overhead watering and water plants at the base",
      "Disinfect tools regularly, especially between plants",
      "Practice crop rotation to reduce the risk of soil-borne pathogens",
      "Mulch to prevent soil splash and keep foliage dry",
      "Monitor plants frequently for early signs of infection and treat promptly",
      "Use organic treatments like neem oil or Bacillus subtilis for early-stage control",
    ],
    causes: [
      "Caused by the fungal pathogen *Phytophthora infestans*",
      "Spread by wind, rain, or infected plant material",
      "Humidity, poor airflow, and prolonged wet conditions favor spore spread",
      "Infected seeds or transplants can introduce the pathogen",
      "Infected tools or contaminated soil contribute to pathogen spread",
    ],
    severity: "high",
  },
  {
    label: "Tomato___Tomato_mosaic_virus",
    crop: "Tomato",
    disease: "Tomato mosaic virus",
    remedies: [
      "Remove and destroy infected plants immediately to prevent further spread",
      "Use disease-resistant tomato varieties",
      "Disinfect tools regularly, especially between handling infected and healthy plants",
      "Avoid mechanical transmission by not handling plants in rainy or humid conditions",
      "Control insect vectors, like aphids, that can spread the virus",
      "Avoid overhead watering to reduce leaf wetness",
      "Rotate crops and practice good soil management to reduce overall pathogen load",
      "Clean up plant debris thoroughly after harvest",
      "Avoid planting tomatoes in areas where the virus was previously present",
    ],
    causes: [
      "Caused by the *Tobacco mosaic virus* (TMV) or *Tomato mosaic virus* (ToMV)",
      "Spread through mechanical transmission, infected seeds, and insect vectors",
      "Humid conditions can exacerbate viral spread",
      "Infected tools, hands, and debris contribute to further contamination",
    ],
    severity: "high",
  },
  {
    label: "Strawberry___healthy",
    crop: "Strawberry",
    disease: "healthy",
    remedies: [
      "Ensure good drainage and water at the base of plants to avoid wet foliage",
      "Regularly monitor for pests and remove them promptly",
      "Mulch to maintain soil moisture and reduce disease risk",
      "Ensure proper plant spacing to improve airflow",
      "Use disease-resistant strawberry varieties for better resilience",
      "Remove old or dead leaves to prevent harboring potential pathogens",
      "Disinfect tools regularly to avoid cross-contamination",
      "Rotate crops yearly to avoid soil-borne disease build-up",
      "Use organic treatments like neem oil for pest and fungal control if needed",
    ],
    causes: [
      "Healthy strawberry growth supported by proper care and maintenance",
      "Adequate spacing and sunlight, combined with good irrigation, support plant vitality",
      "Regular pest management ensures the prevention of common strawberry diseases",
    ],
    severity: "low",
  },
  {
    label: "Apple___healthy",
    crop: "Apple",
    disease: "healthy",
    remedies: [
      "Ensure proper plant spacing to allow adequate airflow",
      "Use disease-resistant apple varieties for better protection",
      "Monitor regularly for pests or disease outbreaks",
      "Maintain consistent soil moisture without overwatering",
      "Prune dead or diseased wood promptly to improve plant health",
      "Disinfect tools regularly to prevent cross-contamination",
      "Mulch around the base of the tree to maintain moisture and suppress weeds",
      "Apply organic treatments like neem oil or diatomaceous earth if pests are detected",
    ],
    causes: [
      "Healthy growth from proper care, adequate sunlight, and good irrigation practices",
      "Monitoring for pests and early disease signs helps maintain overall health",
      "Mulching, pruning, and maintaining soil health reduce disease risks",
    ],
    severity: "low",
  },
  {
    label: "Grape___Black_rot",
    crop: "Grape",
    disease: "Black rot",
    remedies: [
      "Remove and destroy infected fruit, leaves, and stems to reduce spore spread",
      "Apply fungicides specific to black rot, like those with *boscalid* or *pyraclostrobin*",
      "Ensure proper spacing between vines to improve airflow and reduce humidity",
      "Use resistant grape varieties where possible",
      "Avoid overhead watering to keep foliage dry",
      "Disinfect tools regularly to avoid spreading infection",
      "Remove old leaves and debris in late fall to minimize overwintering spores",
      "Practice crop rotation and use clean planting material",
    ],
    causes: [
      "Caused by the fungus *Guignardia bidwellii*",
      "Spread through rain, irrigation water, and infected plant material",
      "Wet conditions and high humidity facilitate the growth of the pathogen",
      "Infected debris can harbor the fungus and contribute to future outbreaks",
    ],
    severity: "medium",
  },
  {
    label: "Potato___Early_blight",
    crop: "Potato",
    disease: "Early blight",
    remedies: [
      "Remove and destroy infected leaves promptly to prevent further spread",
      "Apply fungicides with active ingredients such as *chlorothalonil* or *maneb*",
      "Ensure proper plant spacing to allow for good airflow and reduce humidity",
      "Avoid overhead watering to minimize leaf wetness",
      "Rotate crops each season to reduce the risk of soil-borne pathogens",
      "Use disease-resistant potato varieties",
      "Disinfect tools regularly to avoid spreading spores",
      "Mulch around plants to protect them from soil splash and moisture stress",
      "Monitor plants for early signs and treat them as soon as they appear",
    ],
    causes: [
      "Caused by the fungus *Alternaria solani*",
      "Spread by rain, irrigation water, or contaminated equipment",
      "High humidity and poor airflow encourage spore formation and spread",
      "Fungal spores can be carried by insects, tools, or even contaminated soil",
    ],
    severity: "high",
  },
  {
    label: "Cherry_(including_sour)___healthy",
    crop: "Cherry (including sour)",
    disease: "healthy",
    remedies: [
      "Ensure proper spacing between trees for adequate airflow",
      "Use disease-resistant cherry varieties",
      "Prune dead or diseased wood promptly to avoid spread",
      "Disinfect tools regularly, especially between trees",
      "Ensure balanced irrigation, avoiding waterlogging or drought stress",
      "Monitor trees for pests and remove any infected branches or leaves",
      "Mulch to maintain soil moisture and suppress weeds",
      "Rotate crops and clean up fallen fruit and leaves",
      "Monitor trees for early signs of stress or disease",
      "Use organic treatments like neem oil if pest problems arise",
    ],
    causes: [
      "Healthy cherry trees need consistent care, pest management, and good growing conditions",
      "Proper sunlight and airflow prevent fungal and bacterial outbreaks",
      "Regularly removing debris and fallen leaves reduces pathogen buildup",
    ],
    severity: "low",
  },
  {
    label: "Corn_(maize)___Common_rust_",
    crop: "Corn",
    disease: "Common rust",
    remedies: [
      "Remove and destroy infected leaves to reduce spore spread",
      "Apply rust-specific fungicides like triazoles or strobilurins",
      "Ensure proper plant spacing to improve airflow and reduce humidity",
      "Use resistant corn varieties where available",
      "Avoid overhead watering to keep foliage dry",
      "Disinfect tools between plants to prevent disease transmission",
      "Practice crop rotation to avoid pathogen buildup in soil",
      "Mulch to reduce soil splash and protect lower leaves",
      "Monitor corn regularly for early signs of rust",
      "Use organic treatments like neem oil or sulfur-based fungicides for mild infections",
    ],
    causes: [
      "Caused by the fungal pathogen *Puccinia sorghi*",
      "Spread via wind-borne spores from infected plants",
      "Humidity and dense plantings increase infection risk",
      "Infected seeds or transplants can introduce the pathogen",
    ],
    severity: "medium",
  },
  {
    label: "Grape___Esca_(Black_Measles)",
    crop: "Grape",
    disease: "Esca (Black Measles)",
    remedies: [
      "Remove and destroy infected leaves, shoots, and grapevines",
      "Apply fungicides specifically for Esca, like *azoxystrobin*",
      "Ensure proper vine spacing to improve airflow and reduce humidity",
      "Use resistant grape varieties where available",
      "Prune dead or infected vine material promptly",
      "Disinfect pruning tools after each cut to avoid spreading spores",
      "Remove old leaves and grape debris from the vineyard",
      "Practice crop rotation and site management to minimize pathogen buildup",
      "Monitor vines regularly for early signs of black rot or esca symptoms",
    ],
    causes: [
      "Caused by fungal pathogens such as *Phaeomoniella chlamydospora* and *Fomitiporia mediterranea*",
      "Spread by infected plant material, tools, and mechanical handling",
      "Wet conditions and poor airflow contribute to fungal growth",
      "Infected wood or vines can act as reservoirs for the fungus",
    ],
    severity: "medium",
  },
  {
    label: "Raspberry___healthy",
    crop: "Raspberry",
    disease: "healthy",
    remedies: [
      "Ensure proper spacing between plants to allow for airflow",
      "Use disease-resistant raspberry varieties",
      "Prune regularly to remove dead or diseased canes",
      "Avoid overhead watering and water at the base of the plants",
      "Mulch around the base to retain moisture and reduce weed pressure",
      "Monitor regularly for pests like aphids and remove them immediately",
      "Disinfect tools to prevent cross-contamination",
      "Practice crop rotation to minimize soil-borne disease risks",
      "Remove fallen fruit or leaves that can harbor pests or pathogens",
    ],
    causes: [
      "Healthy raspberries thrive with proper care, sunlight, and water management",
      "Prevent pests and diseases through regular maintenance and monitoring",
      "Maintaining clean garden practices reduces the risk of fungal or bacterial infections",
    ],
    severity: "low",
  },
  {
    label: "Tomato___Leaf_Mold",
    crop: "Tomato",
    disease: "Leaf Mold",
    remedies: [
      "Remove and destroy infected leaves to reduce disease spread",
      "Apply fungicides specific to leaf mold, such as those containing *chlorothalonil* or *copper sulfate*",
      "Ensure proper spacing between plants to improve airflow and reduce humidity",
      "Avoid overhead watering and water at the base to keep foliage dry",
      "Use resistant tomato varieties if available",
      "Disinfect tools regularly to avoid spreading spores",
      "Mulch around plants to prevent soil splash and protect leaves",
      "Rotate crops yearly to reduce pathogen buildup in the soil",
      "Monitor plants regularly for early signs of leaf mold and treat them promptly",
    ],
    causes: [
      "Caused by the fungus *Cladosporium fulvum*",
      "Spread through rain, irrigation, and infected plant material",
      "Humid conditions and poor ventilation encourage fungal growth",
      "Infected plant debris left in the garden can harbor the fungus",
    ],
    severity: "medium",
  },
  {
    label: "Tomato___Spider_mites Two-spotted_spider_mite",
    crop: "Tomato",
    disease: "Spider mites (Two-spotted spider mite)",
    remedies: [
      "Remove and destroy infected leaves to reduce mite numbers",
      "Apply miticides or insecticidal soap specifically for spider mites",
      "Ensure proper plant spacing to reduce humidity and discourage mite infestations",
      "Use resistant tomato varieties where possible",
      "Avoid overhead watering and provide adequate irrigation at the base",
      "Regularly inspect plants for early signs of spider mite damage",
      "Disinfect tools and equipment to prevent mite spread",
      "Introduce natural predators like ladybugs or predatory mites",
      "Maintain a clean garden by removing infested leaves and plant material",
    ],
    causes: [
      "Caused by the *Tetranychus urticae* spider mite",
      "Spread by wind, irrigation, and infested plant material",
      "High temperatures and low humidity favor spider mite infestations",
      "Inadequate irrigation and overcrowded plants increase susceptibility",
    ],
    severity: "high",
  },
  {
    label: "Pepper,_bell___Bacterial_spot",
    crop: "Pepper, bell",
    disease: "Bacterial spot",
    remedies: [
      "Remove and destroy infected leaves to reduce bacterial spread",
      "Apply copper-based fungicides or bactericides specifically for bacterial spot",
      "Ensure proper spacing between plants to promote airflow and reduce humidity",
      "Use disease-resistant pepper varieties when available",
      "Avoid overhead watering to keep leaves dry and prevent bacterial growth",
      "Disinfect tools between plants to avoid cross-contamination",
      "Rotate crops annually to break the pathogen cycle and reduce soil-borne infection",
      "Mulch around plants to prevent soil splash and reduce pathogen spread",
      "Monitor plants regularly for early signs such as water-soaked lesions on leaves",
      "Use organic treatments like neem oil or biological agents that target bacterial pathogens",
    ],
    causes: [
      "Caused by bacterial pathogens like *Xanthomonas* species",
      "Spread through water splashing, wind, and infected plant material",
      "Humidity, poor airflow, and wet conditions promote bacterial growth",
      "Contaminated tools, soil, and seeds can introduce bacteria into the garden",
      "Overwatering and poor drainage create ideal conditions for bacterial spread",
    ],
    severity: "high",
  },
  {
    label: "Corn_(maize)___healthy",
    crop: "Corn",
    disease: "healthy",
    remedies: [
      "Ensure proper spacing between plants to improve airflow and reduce disease risk",
      "Use disease-resistant corn varieties suited to your local conditions",
      "Practice crop rotation to minimize the risk of soil-borne diseases",
      "Avoid overhead irrigation and water at the base to keep leaves dry",
      "Monitor plants regularly for early signs of disease or pest damage",
      "Disinfect tools regularly to prevent the spread of potential pathogens",
      "Mulch around the base of plants to conserve moisture and reduce weed competition",
      "Maintain proper soil fertility and avoid over-fertilizing, which can stress plants",
      "Ensure proper drainage to avoid waterlogging and root rot",
      "Keep the field clear of debris to reduce harboring pests and diseases",
    ],
    causes: [
      "Healthy corn plants require good air circulation, sunlight, and moisture management",
      "Proper irrigation practices help prevent fungal or bacterial growth on the leaves",
      "Diseases are often introduced through infected seeds or contaminated tools",
      "Rotating crops and removing plant debris helps reduce the risk of soil-borne pathogens",
    ],
    severity: "low",
  },
] as const;
